CREATE TABLE IF NOT EXISTS articles (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    product_name VARCHAR(160) NOT NULL,
    description VARCHAR(2000) NOT NULL,
    price DECIMAL(12,2) NOT NULL,
    image_url VARCHAR(600) NOT NULL,
    boutique_name VARCHAR(160) NOT NULL,
    category VARCHAR(100) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at DATETIME NULL,
    updated_at DATETIME NULL,
    INDEX idx_articles_active (active),
    INDEX idx_articles_created_at (created_at)
);

CREATE TABLE IF NOT EXISTS purchase_orders (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    transaction_id VARCHAR(70) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    article_id BIGINT NOT NULL,
    credit_request_id BIGINT NULL,
    article_name VARCHAR(160) NOT NULL,
    boutique_name VARCHAR(160) NOT NULL,
    category VARCHAR(100) NOT NULL,
    total_price DECIMAL(12,2) NOT NULL,
    down_payment DECIMAL(12,2) NOT NULL,
    financed_amount DECIMAL(12,2) NOT NULL,
    interest_amount DECIMAL(12,2) NOT NULL DEFAULT 0.00,
    merchant_margin_rate DECIMAL(8,4) NOT NULL DEFAULT 0.0000,
    monthly_amount DECIMAL(12,2) NULL,
    installment_months INT NULL,
    payment_type VARCHAR(20) NOT NULL,
    status VARCHAR(30) NOT NULL,
    merchant_paid BOOLEAN NOT NULL DEFAULT FALSE,
    merchant_payout_reference VARCHAR(120) NULL,
    merchant_paid_at DATETIME NULL,
    created_at DATETIME NULL,
    updated_at DATETIME NULL,
    CONSTRAINT fk_po_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_po_article FOREIGN KEY (article_id) REFERENCES articles(id),
    CONSTRAINT fk_po_credit_request FOREIGN KEY (credit_request_id) REFERENCES credit_requests(id),
    INDEX idx_po_user_created_at (user_id, created_at),
    INDEX idx_po_payment_type_created_at (payment_type, created_at)
);

CREATE TABLE IF NOT EXISTS invoices (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    invoice_number VARCHAR(70) NOT NULL UNIQUE,
    transaction_id VARCHAR(70) NOT NULL UNIQUE,
    order_id BIGINT NOT NULL UNIQUE,
    user_id BIGINT NOT NULL,
    client_name VARCHAR(180) NOT NULL,
    client_email VARCHAR(180) NOT NULL,
    client_phone VARCHAR(40) NULL,
    article_name VARCHAR(180) NOT NULL,
    boutique_name VARCHAR(180) NOT NULL,
    total_price DECIMAL(12,2) NOT NULL,
    payment_type VARCHAR(20) NOT NULL,
    number_of_installments INT NOT NULL,
    purchase_date DATETIME NOT NULL,
    status VARCHAR(20) NOT NULL,
    statement VARCHAR(800) NOT NULL,
    created_at DATETIME NULL,
    updated_at DATETIME NULL,
    CONSTRAINT fk_inv_order FOREIGN KEY (order_id) REFERENCES purchase_orders(id),
    CONSTRAINT fk_inv_user FOREIGN KEY (user_id) REFERENCES users(id),
    INDEX idx_invoices_purchase_date (purchase_date)
);

CREATE TABLE IF NOT EXISTS admin_notifications (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(180) NOT NULL,
    message VARCHAR(2500) NOT NULL,
    type VARCHAR(40) NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    order_id BIGINT NULL,
    transaction_id VARCHAR(70) NULL,
    created_at DATETIME NULL,
    updated_at DATETIME NULL,
    INDEX idx_admin_notifications_read (is_read),
    INDEX idx_admin_notifications_created_at (created_at)
);
