package com.creaditn.creaditnbackend.security;

import jakarta.servlet.FilterChain;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.security.web.authentication.WebAuthenticationDetailsSource;
import org.springframework.stereotype.Component;
import org.springframework.web.filter.OncePerRequestFilter;

import java.io.IOException;
import java.util.List;

/**
 * Validates the X-Admin-Token header for /api/admin/** endpoints.
 * Admin tokens are generated by AdminController.adminLogin() as "admin-session-{timestamp}".
 */
@Component
public class AdminAuthFilter extends OncePerRequestFilter {

    private static final String ADMIN_TOKEN_HEADER = "X-Admin-Token";
    private static final String ADMIN_TOKEN_PREFIX = "admin-session-";

    @Override
    protected void doFilterInternal(HttpServletRequest request,
                                    HttpServletResponse response,
                                    FilterChain filterChain)
            throws ServletException, IOException {

        String path = request.getServletPath();

        // Only apply to admin paths and protected KYC evidence files.
        boolean adminPath = path.startsWith("/api/admin/") && !path.equals("/api/admin/login");
        boolean kycEvidencePath = path.startsWith("/api/files/kyc/");
        if (!adminPath && !kycEvidencePath) {
            filterChain.doFilter(request, response);
            return;
        }

        String adminToken = request.getHeader(ADMIN_TOKEN_HEADER);

        if (adminToken != null && adminToken.startsWith(ADMIN_TOKEN_PREFIX)
                && SecurityContextHolder.getContext().getAuthentication() == null) {
            UsernamePasswordAuthenticationToken authentication =
                    new UsernamePasswordAuthenticationToken(
                            "admin",
                            null,
                            List.of(new SimpleGrantedAuthority("ROLE_ADMIN"))
                    );
            authentication.setDetails(new WebAuthenticationDetailsSource().buildDetails(request));
            SecurityContextHolder.getContext().setAuthentication(authentication);
        }

        filterChain.doFilter(request, response);
    }
}
